name: acom
description: "ACOM - Always Count On Me. Tu compañía emocional."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sounds/rain.mp3
    - assets/sounds/ocean.mp3
    - assets/sounds/forest.mp3
    - assets/sounds/fire.mp3
    - assets/sounds/wind.mp3
    - assets/sounds/cafe.mp3
    - assets/sounds/tibetan.mp3
    - assets/sounds/white.mp3